[tool.black]
line-length = 120
exclude = '''
/(
    \.git
  | venv
  | \.venv
  | env
  | \.env
  | _build
  | build
  | dist
)/
'''

[tool.poetry]
name = "ngi-kof-parser"
version = "0.0.6"
description = "Parser of KOF files. Follows Norkart's KOF 2.0 specification from 2005."
authors = ["Jostein Leira <jostein@leira.net>"]
readme = "README.md"

[[tool.poetry.source]]
name = "ngi-fm"
url = "https://pkgs.dev.azure.com/ngi001/277b2f77-691a-4d92-bd89-8e7cac121676/_packaging/fieldmanager/pypi/simple/"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.9.0"
ngi-projector = "^0.0.3"

[tool.poetry.dev-dependencies]
black = "*"
pytest = "*"
pytest-cov = "*"
pytest-azurepipelines = "*"
mypy = "*"
bandit = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
